/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lojainstrumentos.view;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import lojainstrumentos.dao.ProdutosDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lojainstrumentos.model.Produto;

/**
 *
 * @author alves
 */
public class CadastroProduto extends javax.swing.JDialog {

    /**
     * Creates new form CadastroProduto
     */
    Produto objAltProduto;

    public void readTabela() {
        //Chama DAO para consulta
        ArrayList<Produto> lista = ProdutosDAO.listarProduto();

        DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();

        //Zera tabela
        modelo.setRowCount(0);

        //Adicionar linhas com for
        for (Produto item : lista) {
            modelo.addRow(new String[]{
                String.valueOf(item.getCodigoProd()),
                String.valueOf(item.getNomeProd()),
                String.valueOf(item.getQuantidadeProd()),
                String.valueOf(item.getPrecoProd()),
                String.valueOf(item.getDescricaoProd())
            }
            );
        }
    }

    public CadastroProduto() {
        initComponents();
    }

    public CadastroProduto(Produto obj) {
        //passa os dados para a classe produto
        nome_produto.setText(String.valueOf(obj.getNomeProd()));
        campo_quantidade.setText(String.valueOf(obj.getQuantidadeProd()));
        descricao_produto.setText(String.valueOf(obj.getDescricaoProd()));
        cod_produto.setText(String.valueOf(obj.getCodigoProd()));
        preco_produto.setText(String.valueOf(obj.getPrecoProd()));

        objAltProduto = obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCadastroProdutos = new javax.swing.JLabel();
        lblNomeProduto = new javax.swing.JLabel();
        nome_produto = new javax.swing.JTextField();
        lblCodProduto = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        descricao_produto = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        preco_produto = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        inserir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        txtConsultar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaConsultaProd = new javax.swing.JTable();
        labelStatus = new javax.swing.JLabel();
        campo_quantidade = new javax.swing.JTextField();
        cod_produto = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(5, 41, 32));
        setLocation(new java.awt.Point(600, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(5, 41, 32));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));

        lblCadastroProdutos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCadastroProdutos.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastroProdutos.setText("CADASTRO PRODUTOS");

        lblNomeProduto.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeProduto.setText("Nome do produto :");

        nome_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_produtoActionPerformed(evt);
            }
        });
        nome_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nome_produtoKeyTyped(evt);
            }
        });

        lblCodProduto.setForeground(new java.awt.Color(255, 255, 255));
        lblCodProduto.setText("Cod. Produto :");

        lblPreco.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco.setText("Preço :");

        lblDescricao.setForeground(new java.awt.Color(255, 255, 255));
        lblDescricao.setText("Descriçao do produto :");

        descricao_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricao_produtoActionPerformed(evt);
            }
        });

        lblQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantidade.setText("Quantidade :");

        try {
            preco_produto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$####,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        preco_produto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                preco_produtoFocusLost(evt);
            }
        });
        preco_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preco_produtoActionPerformed(evt);
            }
        });
        preco_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                preco_produtoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                preco_produtoKeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        inserir.setBackground(new java.awt.Color(136, 115, 70));
        inserir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inserir.setForeground(new java.awt.Color(255, 255, 255));
        inserir.setText("Inserir");
        inserir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(136, 115, 70));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(136, 115, 70));
        btnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserir)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnExcluir, inserir});

        tabelaProdutos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo ", "Nome ", "Quantidade", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        btnConsultar.setBackground(new java.awt.Color(136, 115, 70));
        btnConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        tabelaConsultaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Produto", "Produto", "Quantidade", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaConsultaProd);

        labelStatus.setForeground(new java.awt.Color(255, 0, 0));

        campo_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_quantidadeActionPerformed(evt);
            }
        });
        campo_quantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_quantidadeKeyTyped(evt);
            }
        });

        cod_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_produtoActionPerformed(evt);
            }
        });
        cod_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cod_produtoKeyTyped(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(136, 115, 70));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDescricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descricao_produto))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCodProduto)
                                    .addComponent(lblNomeProduto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome_produto, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(cod_produto))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(lblQuantidade))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(lblPreco)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(preco_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCadastroProdutos)
                                    .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblCadastroProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeProduto)
                    .addComponent(lblQuantidade)
                    .addComponent(nome_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodProduto)
                    .addComponent(lblPreco)
                    .addComponent(preco_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(descricao_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada = tabelaProdutos.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha antes de deletar");
        } else {
        DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
        
        //int codigo = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());
        /*int[] selectedRows = tabelaProdutos.getSelectedRows(); 
        for (int i = 0; i < selectedRows.length; i++) {
        System.out.println(tabelaProdutos.getValueAt(selectedRows[i], 0).toString());
        }*/
        int codigo = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());
        
        //Chamar a DAO no método excluir
        boolean retorno = ProdutosDAO.deletarProduto(codigo);
        
        if(retorno){
            JOptionPane.showMessageDialog(rootPane, "Produto exluido com sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Falha ao excluir produto!");
        }
        }
        
        //readTabela();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void descricao_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricao_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricao_produtoActionPerformed

    private void inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirActionPerformed

        /*DefaultTableModel cadProdutos = (DefaultTableModel) tabelaCadProdutos.getModel();
        Object[] dados = {nome_produto.getText(), campo_quantidade.getText(),
                          cod_produto.getText(), descricao_produto.getText()};
        cadProdutos.addRow(dados);*/
        //validar campos obrigatorio
        if (nome_produto.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo produto nao pode estar vazio!");
            return;
        }

        if (campo_quantidade.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo quantidade nao pode estar vazio!");
            return;
        }

        if (cod_produto.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo código produto nao pode estar vazio!");
            return;
        }

        if (descricao_produto.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo descrição nao pode estar vazio!");
            return;
        }
        if (preco_produto.getText().replace(",", "").replace("R$", "").trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo preço nao pode estar vazio!");
            return;
        }

        if (objAltProduto != null) {

            objAltProduto.setNomeProduto(nome_produto.getText());
            objAltProduto.setDescricaoProd(descricao_produto.getText());
            objAltProduto.setPreco(Double.parseDouble(preco_produto.getText().replace(",", ".").replace("R$", "")));
            objAltProduto.setQuantidadeProduto(Integer.parseInt(campo_quantidade.getText()));
            objAltProduto.setCodigoProduto(Integer.parseInt(cod_produto.getText()));

            //Chama a DAO
            boolean retorno = ProdutosDAO.atualizarProduto(objAltProduto);

            if (retorno) {
                JOptionPane.showMessageDialog(rootPane, "Atualizado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao atualizar!");
            }

        } else {
            //Incluir no BD
            Produto obj = new Produto();
            //ProdutosDAO dao = new ProdutosDAO();
            //Produto obj = new Produto(nome, descricao, preco, quantidade);
            obj.setCodigoProduto(Integer.parseInt(cod_produto.getText()));
            obj.setNomeProduto(nome_produto.getText());
            obj.setDescricaoProd(descricao_produto.getText());
            obj.setPreco(Double.parseDouble(preco_produto.getText().replace(",", ".").replace("R$", "")));
            obj.setQuantidadeProduto(Integer.parseInt(campo_quantidade.getText()));
            

            //Implementar DAO
            boolean retorno = ProdutosDAO.salvarProduto(obj);

            if (retorno) {
                JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao salvar!");
            }
        }

    }//GEN-LAST:event_inserirActionPerformed

    private void nome_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_produtoActionPerformed

    private void preco_produtoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_preco_produtoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_preco_produtoFocusLost

    private void preco_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preco_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preco_produtoActionPerformed

    private void preco_produtoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_preco_produtoKeyPressed

    }//GEN-LAST:event_preco_produtoKeyPressed

    private void preco_produtoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_preco_produtoKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            this.labelStatus.setText("Somente números no preço!");
        }

        if (preco_produto.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Máximo de 10   caracteres atingido!");
        }

    }//GEN-LAST:event_preco_produtoKeyTyped

    private void campo_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_quantidadeActionPerformed

    private void campo_quantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_quantidadeKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            this.labelStatus.setText("Somente números na quantidade!");
        }

        if (campo_quantidade.getText().length() >= 3) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Máximo de 3 caracteres atingido!");
        }
    }//GEN-LAST:event_campo_quantidadeKeyTyped

    private void nome_produtoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome_produtoKeyTyped
        char c = evt.getKeyChar();
        if (((c < 'A') || (c > 'Z')) && ((c < 'a') || (c > 'z')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            this.labelStatus.setText("Somente letras no nome!");
        }
    }//GEN-LAST:event_nome_produtoKeyTyped

    private void cod_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_produtoActionPerformed

    }//GEN-LAST:event_cod_produtoActionPerformed

    private void cod_produtoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cod_produtoKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            this.labelStatus.setText("Somente números no código do produto!");
        }

        if (cod_produto.getText().length() >= 9) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Máximo de 9 caracteres atingido!");
        }
    }//GEN-LAST:event_cod_produtoKeyTyped

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        if (nome_produto.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo produto nao pode estar vazio!");
            return;
        }

        if (campo_quantidade.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo quantidade nao pode estar vazio!");
            return;
        }

        if (cod_produto.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo código produto nao pode estar vazio!");
            return;
        }

        if (descricao_produto.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo descrição nao pode estar vazio!");
            return;
        }
        if (preco_produto.getText().replace(",", "").replace("R$", "").trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo preço nao pode estar vazio!");
            return;
        }

        Produto objAlterar = new Produto();

        objAlterar.setNomeProduto(nome_produto.getText());
        objAlterar.setDescricaoProd(descricao_produto.getText());
        objAlterar.setPreco(Double.parseDouble(preco_produto.getText().replace(",", ".").replace("R$", "")));
        objAlterar.setQuantidadeProduto(Integer.parseInt(campo_quantidade.getText()));
        objAlterar.setCodigoProduto(Integer.parseInt(cod_produto.getText()));

        //Chama a DAO
        boolean retorno = ProdutosDAO.atualizarProduto(objAlterar);

        if (retorno) {
            JOptionPane.showMessageDialog(rootPane, "Atualizado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro ao atualizar!");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        readTabela();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JTextField campo_quantidade;
    private javax.swing.JTextField cod_produto;
    private javax.swing.JTextField descricao_produto;
    private javax.swing.JButton inserir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel lblCadastroProdutos;
    private javax.swing.JLabel lblCodProduto;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JTextField nome_produto;
    private javax.swing.JFormattedTextField preco_produto;
    private javax.swing.JTable tabelaConsultaProd;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTextField txtConsultar;
    // End of variables declaration//GEN-END:variables
}
