/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lojainstrumentos.view;

/**
 *
 * @author 55119
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        mnuCadastros = new javax.swing.JMenu();
        mnuCadastroCliente = new javax.swing.JMenuItem();
        mnuCadastroProduto = new javax.swing.JMenuItem();
        mnuComprar = new javax.swing.JMenu();
        mnuProdutos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuRelatorio = new javax.swing.JMenuItem();
        mnuConsultaCli = new javax.swing.JMenuItem();
        mnuConsultaVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empório da Musica");
        setLocation(new java.awt.Point(600, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(5, 41, 32));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(5, 41, 32));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("BEM VINDOS AO EMPORIO DA MUSICA");
        lblTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));

        Menu.setBorder(null);
        Menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        mnuCadastros.setText("Cadastros");

        mnuCadastroCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnuCadastroCliente.setText("Cadastro Cliente");
        mnuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroClienteActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuCadastroCliente);

        mnuCadastroProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnuCadastroProduto.setText("Cadatro Produto");
        mnuCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroProdutoActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuCadastroProduto);

        Menu.add(mnuCadastros);

        mnuComprar.setText("Comprar");

        mnuProdutos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnuProdutos.setText("Produtos");
        mnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutosActionPerformed(evt);
            }
        });
        mnuComprar.add(mnuProdutos);

        Menu.add(mnuComprar);

        jMenu1.setText("Consultas");

        mnuRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnuRelatorio.setText("Relatorio de Vendas");
        mnuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRelatorioActionPerformed(evt);
            }
        });
        jMenu1.add(mnuRelatorio);

        mnuConsultaCli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnuConsultaCli.setText("Consulta Cliente");
        mnuConsultaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaCliActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsultaCli);

        mnuConsultaVenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnuConsultaVenda.setText("Consultar Venda");
        mnuConsultaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaVendaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsultaVenda);

        Menu.add(jMenu1);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroClienteActionPerformed
        TelaCadastro objCadastro = new TelaCadastro();
        objCadastro.setModal(true);
        objCadastro.setVisible(true);
    }//GEN-LAST:event_mnuCadastroClienteActionPerformed

    private void mnuCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroProdutoActionPerformed
        CadastroProduto objCadastroProd = new CadastroProduto();
        objCadastroProd.setModal(true);
        objCadastroProd.setVisible(true);
    }//GEN-LAST:event_mnuCadastroProdutoActionPerformed

    private void mnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutosActionPerformed
        TelaVendaProdutos objViewVenda = new TelaVendaProdutos();
        objViewVenda.setModal(true);
        objViewVenda.setVisible(true);
    }//GEN-LAST:event_mnuProdutosActionPerformed

    private void mnuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRelatorioActionPerformed
        TelaRelatorioVendas objRelatorioVenda = new TelaRelatorioVendas();
        objRelatorioVenda.setModal(true);
        objRelatorioVenda.setVisible(true);
    }//GEN-LAST:event_mnuRelatorioActionPerformed

    private void mnuConsultaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaCliActionPerformed
       ConsultaCliente objConsultaCli = new ConsultaCliente();
       objConsultaCli.setModal(true);
       objConsultaCli.setVisible(true);
    }//GEN-LAST:event_mnuConsultaCliActionPerformed

    private void mnuConsultaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaVendaActionPerformed
        TelaPesquisaVendas objConsultaVenda = new TelaPesquisaVendas();
        objConsultaVenda.setModal(true);
        objConsultaVenda.setVisible(true);
    }//GEN-LAST:event_mnuConsultaVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem mnuCadastroCliente;
    private javax.swing.JMenuItem mnuCadastroProduto;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenu mnuComprar;
    private javax.swing.JMenuItem mnuConsultaCli;
    private javax.swing.JMenuItem mnuConsultaVenda;
    private javax.swing.JMenuItem mnuProdutos;
    private javax.swing.JMenuItem mnuRelatorio;
    // End of variables declaration//GEN-END:variables
}
