/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lojainstrumentos.lojainstrumentos;

import javax.swing.JOptionPane;


/**
 *
 * @author 55119
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        genero = new javax.swing.ButtonGroup();
        estadoCivil = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campo_nome = new javax.swing.JTextField();
        campo_cpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campo_endereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campo_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        G_masculino = new javax.swing.JRadioButton();
        G_feminino = new javax.swing.JRadioButton();
        jbtnSolteiro = new javax.swing.JRadioButton();
        jbtnCasado = new javax.swing.JRadioButton();
        jbtnSeparado = new javax.swing.JRadioButton();
        jbtnViuvo = new javax.swing.JRadioButton();
        campo_data = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        Cadastrar = new javax.swing.JButton();
        campo_telefone = new javax.swing.JFormattedTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(5, 41, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome Completo :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        campo_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nomeActionPerformed(evt);
            }
        });
        jPanel1.add(campo_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 279, -1));

        try {
            campo_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_cpfActionPerformed(evt);
            }
        });
        jPanel1.add(campo_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 279, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPF :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Endereço :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        campo_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_enderecoActionPerformed(evt);
            }
        });
        jPanel1.add(campo_endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 279, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefone ou Celular :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-mail :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        campo_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_emailActionPerformed(evt);
            }
        });
        jPanel1.add(campo_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 279, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Género :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estado civíl :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        genero.add(G_masculino);
        G_masculino.setForeground(new java.awt.Color(255, 255, 255));
        G_masculino.setText("Masculino");
        G_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_masculinoActionPerformed(evt);
            }
        });
        jPanel1.add(G_masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        genero.add(G_feminino);
        G_feminino.setForeground(new java.awt.Color(255, 255, 255));
        G_feminino.setText("Femenino");
        G_feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_femininoActionPerformed(evt);
            }
        });
        jPanel1.add(G_feminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        estadoCivil.add(jbtnSolteiro);
        jbtnSolteiro.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSolteiro.setText("solteiro(a)");
        jbtnSolteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSolteiroActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSolteiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        estadoCivil.add(jbtnCasado);
        jbtnCasado.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCasado.setText("casado(a)");
        jbtnCasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCasadoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        estadoCivil.add(jbtnSeparado);
        jbtnSeparado.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSeparado.setText("separado(a)");
        jPanel1.add(jbtnSeparado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        estadoCivil.add(jbtnViuvo);
        jbtnViuvo.setForeground(new java.awt.Color(255, 255, 255));
        jbtnViuvo.setText("viuvo (a)");
        jbtnViuvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViuvoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnViuvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        try {
            campo_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_dataActionPerformed(evt);
            }
        });
        jPanel1.add(campo_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 106, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data de nascimento :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        Cadastrar.setBackground(new java.awt.Color(136, 115, 70));
        Cadastrar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        Cadastrar.setText("CADASTRAR");
        Cadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 150, 40));

        try {
            campo_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(campo_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        
        //validação de quantidade de 
        if (campo_nome.getText().isEmpty()&& campo_nome.getText().length()>10){
         JOptionPane.showMessageDialog(rootPane,"não ultilizar mais de 10 caracteres!");
        }
        //validar campos obrigatorio
        if(campo_nome.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite o Nome");
            return;
        }
        if(campo_email.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite o Email");
        }
        if(campo_endereco.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite o endereço");
        }
         if(campo_data.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite o data de nascimento");
        }
        if(campo_telefone.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite o telefone");
            
          if(campo_cpf.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Digite o CPF");
        }
        
    }//GEN-LAST:event_CadastrarActionPerformed
    }
    private void campo_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_dataActionPerformed
         //validação de quantidade de 
        if (campo_data.getText().isEmpty()&& campo_data.getText().length()>6){
         JOptionPane.showMessageDialog(rootPane,"não ultilizar mais de 6 caracteres!");
                   
        }
    }//GEN-LAST:event_campo_dataActionPerformed

    private void jbtnViuvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViuvoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnViuvoActionPerformed

    private void jbtnCasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCasadoActionPerformed

    private void jbtnSolteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSolteiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSolteiroActionPerformed

    private void G_femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_femininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G_femininoActionPerformed

    private void G_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_masculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G_masculinoActionPerformed

    private void campo_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_enderecoActionPerformed
        //validação de quantidade de 
        if (campo_endereco.getText().isEmpty()&& campo_endereco.getText().length()>50){
         JOptionPane.showMessageDialog(rootPane,"não ultilizar mais de 50 caracteres!");
                    
            
        }
    }//GEN-LAST:event_campo_enderecoActionPerformed

    private void campo_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_cpfActionPerformed
       //não esta limitando qtdade 
       //validação de quantidade de 
        if (campo_cpf.getText().isEmpty()&& campo_cpf.getText().length()>11){
         JOptionPane.showMessageDialog(rootPane,"CPF tem apenas 11 digitos ");
                    
            
        }

    }//GEN-LAST:event_campo_cpfActionPerformed

    private void campo_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nomeActionPerformed

        /*validação de quantidade de 
        if (campo_nome.getText().isEmpty()&& campo_nome.getText().length()>5){
         JOptionPane.showMessageDialog(rootPane,"não ultilizar mais de 50 caracteres!");
                    
            
        }*/

    }//GEN-LAST:event_campo_nomeActionPerformed

    private void campo_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JRadioButton G_feminino;
    private javax.swing.JRadioButton G_masculino;
    private javax.swing.JFormattedTextField campo_cpf;
    private javax.swing.JFormattedTextField campo_data;
    private javax.swing.JTextField campo_email;
    private javax.swing.JTextField campo_endereco;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JFormattedTextField campo_telefone;
    private javax.swing.ButtonGroup estadoCivil;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton jbtnCasado;
    private javax.swing.JRadioButton jbtnSeparado;
    private javax.swing.JRadioButton jbtnSolteiro;
    private javax.swing.JRadioButton jbtnViuvo;
    // End of variables declaration//GEN-END:variables
}
